# Generated by Django 4.1 on 2022-08-26 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_candidato', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf_do_candidato', models.CharField(max_length=15)),
                ('sexo_candidato', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('empresa_onde_trabalhou', models.CharField(max_length=50)),
                ('cargo_exercido', models.CharField(max_length=50)),
                ('inicio_do_emprego', models.DateField()),
                ('data_da_demissao', models.DateField()),
                ('descricao_de_atividades', models.TextField()),
                ('experiencia', models.CharField(max_length=12)),
                ('status_fundamental', models.CharField(max_length=12)),
                ('status_medio', models.CharField(max_length=12)),
                ('status_tecnico', models.CharField(max_length=12)),
                ('curso_tecnico', models.CharField(max_length=50)),
                ('instituicao_do_curso_tecnico', models.CharField(max_length=50)),
                ('inicio_do_curso_tecnico', models.DateField()),
                ('termino_do_curso_tecnico', models.DateField()),
                ('grau_superior', models.CharField(max_length=12)),
                ('curso_superior', models.CharField(max_length=50)),
                ('instituicao_do_curso_superior', models.CharField(max_length=50)),
                ('inicio_do_curso_superior', models.DateField()),
                ('termino_do_curso_superior', models.DateField()),
                ('idioma', models.CharField(max_length=12)),
                ('nivel_idioma', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado'), ('F', 'Fluente')], max_length=1)),
                ('data_atual', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data_atualizacao', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'tb_candidatos',
            },
        ),
    ]
