# Generated by Django 4.1 on 2022-09-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=20)),
                ('nivel_prog', models.CharField(blank=True, max_length=20)),
                ('nivel_ing', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(blank=True, max_length=20)),
                ('ramo', models.CharField(blank=True, max_length=20)),
                ('localizacao', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
