# Generated by Django 4.1 on 2022-10-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0003_ano_areadeinteresse_conquista_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='nivel_ing',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='nivel_prog',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='ramo',
        ),
    ]
