# Generated by Django 4.1 on 2022-10-18 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0004_remove_candidato_nivel_ing_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidato',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
