# Generated by Django 4.1 on 2022-10-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_perfil_empresa', models.ImageField(blank=True, upload_to='imgperfil/%d/%m/%Y')),
                ('razao_social', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=15)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=19)),
                ('celular', models.CharField(max_length=19)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=15)),
                ('ramo_de_atividade', models.CharField(max_length=150)),
                ('descricao_empresa', models.TextField()),
            ],
        ),
    ]
