# Generated by Django 4.1 on 2022-10-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofissional',
            name='contratacao',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tipocontratacao',
            name='contratacao',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='tipotrabalho',
            name='trabalho',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='area_atuacao',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='nome_vaga',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='perfil_profissional',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='tipo_contratacao',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='tipo_trabalho',
            field=models.CharField(max_length=80),
        ),
    ]
