# Generated by Django 4.1 on 2022-09-26 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0002_candidato_empresa'),
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagaSalva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cadidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_cadastro.candidato')),
                ('id_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaga.vagas')),
            ],
        ),
    ]
