# Generated by Django 4.1 on 2022-08-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='logo_empresa',
            field=models.ImageField(blank=True, upload_to='logos/%Y/%m/%d'),
        ),
    ]
