# Generated by Django 4.1 on 2022-10-21 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaga', '0002_alter_perfilprofissional_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='nome_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
