# Generated by Django 4.1 on 2022-09-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_cadastro', '0002_candidato_empresa'),
        ('vaga', '0002_vagasalva'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VagaSalva',
            new_name='VagasSalvas',
        ),
    ]
