# Generated by Django 4.1 on 2022-10-03 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaga', '0003_rename_vagasalva_vagassalvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagassalvas',
            name='id_cadidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
