# Generated by Django 4.1.2 on 2022-10-07 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0004_alter_vagassalvas_id_cadidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='data_vaga',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
