# Generated by Django 4.1 on 2022-10-12 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaga', '0007_alter_vagas_logo_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='VagasCandidatadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cadidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaga.vagas')),
            ],
        ),
    ]
